### PR TITLE
RNBW-2860: Expand verified tokens

### PR DESCRIPTION
**Pull request by welps**
coingecko ∩ coinmarketcap = verified tokens

This will bring our verified token count from 311 -> 4160.

I don't know why we were ignoring TLS validation, but we shouldn't do that since it allows for MITM here.

### CODE REVIEW

**Comment by skylarbarrera** [comment]
i'm super cool with this but we should get confirmation from christian or jin cause they had lots of hesitations last time

**Review by skylarbarrera — APPROVED** [review]
💪

**Comment by welps** [comment]
> i'm super cool with this but we should get confirmation from christian or jin cause they had lots of hesitations last time

ok

**Comment by samisbakedham** [comment]
I agree with this merger entirely! Great work Welps

**Comment by welps** [comment]
We got approval, but if this looks horrible we will revert and bring back when we have more sorting/filtering options

**Pull request merged**
